### PR TITLE
yokotool: add a switch to output a timestamp when reading metrics

### PR DESCRIPTION
**Pull request by mupuf**
Signed-off-by: Martin Peres martin.peres@linux.intel.com

### CODE REVIEW

**Comment by HeliaCo** [comment]
@mupuf 

Hi  Martin,

Thank you for your contribution #1 and apologies for my late feedback.

FYI I am currently implementing a way for yokotool to provide time stamps as well as well as some other types of data that we call "virtual data items" [1]. I will notify you when this new feature is available.

In fact we received a request similar to yours:
- you need yokotool to output "time stamps" while reading data items
- someone else wants yokotool to output "Joules" while reading data items

So I am working on a sustainable solution that should encompass both requests and fit some similar cases we may face in the future.

Best regards,
Helia

[1] "virtual data items" is data that we compute ourselves or provide on-the-fly, as opposed to the data items we read from the power meter

**Comment by mupuf** [comment]
Sounds great! I can keep my local version until you come up with something.

Notify me if you want a review :)

**Comment by HeliaCo** [comment]
Hi Martin,

A new release of Yoko Tool is now available and it provides the support of virtual data items, namely the "time stamp" and "Joules".

So you can getthose data items along with the power, voltage, current, etc.

Apologies for looong time that took me, I hope you'll enjoy this new feature!

Thank you and best regards,
Helia

**Comment by mupuf** [comment]
Wonderful, thanks Helia!

**Pull request closed without merging**
